FORMAT: 1A

# Blocker API
A block based filesystem microservice written in go

# Group API Authentication
All requests must contain an 'Auth Token'.

##Authorization

Authorization is done via a *Authorization* header sent in a request.  Anonymous requests are not allowed.  To authenticate a request, you must sign the request with the shared key when making the request and pass that signature as part of the request.  

Here you can see an example of a Authorization header
```
Authorization=RvPtP0QB7iIun1ehwheD4YUo7+fYfw7/ywl+HsC5Ddk=
```

You construct the signature is built in the following format:

```
authRequestSig = method + "\n" +
                 Date + "\n" +
                 resource
```

This would result in the following signature to be signed:

```
COPY\nWed, 28 Jan 2015 10:42:13 UTC\n/api/v1/blocker/6f90d707-3b6a-4321-b32c-3c1d37915c1b
```

Note that you MUST past the same date value in the request.  Date should be supplied in UTC using RFC1123 format.

```
x-blocker-date=Wed, 28 Jan 2015 10:42:13 UTC
```

  The signature must be exactly in the same order and include the new line character.  

Now encode the signature using the [HMAC-SHA256](http://en.wikipedia.org/wiki/Hash-based_message_authentication_code) algorithm using the shared key.

This will result in a key like this:
```
RvPtP0QB7iIun1ehwheD4YUo7+fYfw7/ywl+HsC5Ddk="
```

Example go code to create the signature

```go
date := time.Now().UTC().Format(time.RFC1123) // UTC time
request.Header.Add("x-blocker-date", date)

authRequestKey := fmt.Sprintf("%s\n%s\n%s", method, date, resource)

// See package http://golang.org/pkg/crypto/hmac/ on how golang creates hmacs
hmac := crypto.GetHmac256(authRequestKey, SharedKey)  

request.Header.Add("Authorization", hmac)
```

# Group Blocker
Blocker related resources of the **Blocker API**

## Creating a BlockedFile [/api/v1/blocker]

### POST BlockedFile [POST]
This is usually done via a form.
+ Request 
    + Header

            Authorization: RvPtP0QB7iIun1ehwheD4YUo7+fYfw7/ywl+HsC5Ddk=
            x-blocker-date: Wed, 28 Jan 2015 10:42:13 UTC
            Content-type: content-type
        
    + Body
        
            Your raw content goes here...

+ Response 200 (application/json)

    [BlockedFile][]

### PUT BlockedFile [PUT]
Typically a raw upload

+ Request 
    + Header

            Authorization: RvPtP0QB7iIun1ehwheD4YUo7+fYfw7/ywl+HsC5Ddk=
            x-blocker-date: Wed, 28 Jan 2015 10:42:13 UTC
            Content-type: content-type
        
    + Body
        
            Your raw content goes here...
            
+ Response 200 (application/json)

  [BlockedFile][]

## BlockedFile [/api/v1/blocker/{id}]
BlockedFile including the block list

+ Parameters
    + id (required, string, `7203f732-0fa4-430c-9763-2ba1b88670cc`) ... Guid `id` of the BlockedFile to perform action with.

+ Model (application/json)

    + Body

            [{
                "id": "dc50dc9a-fd1c-44e6-a54f-a4a228bb1928",
                "fileHash": "e4e21579f6360b35e66dc97b67cd732a3f759623e41e4e077bec039eeb79fd0a",
                "length": 5504597,
                "blocks": [
                    {
                        "position": 1,
                        "hash": "31d10f019a999e30b10c056e1f06d1b356af1e853a0f37e9fc22e283a4cfd76d"
                    },
                    {
                        "position": 2,
                        "hash": "abe9108b2e0169829cc40b4c0668cddf6df04723a4d22cc6e16eb01706904c99"
                    }
                ]
            }]
            
### Get BlockedFile [GET]
Get a specific BlockFile.

+ Request 
    + Header

            Authorization: RvPtP0QB7iIun1ehwheD4YUo7+fYfw7/ywl+HsC5Ddk=
            x-blocker-date: Wed, 28 Jan 2015 10:42:13 UTC

+ Response 200 (application/json)

    [BlockedFile][]

### Copy BlockedFile [COPY]
Copy a BlockedFile.  The returned BlockedFile is the new BlockedFile.

+ Request 
    + Header

            Authorization: RvPtP0QB7iIun1ehwheD4YUo7+fYfw7/ywl+HsC5Ddk=
            x-blocker-date: Wed, 28 Jan 2015 10:42:13 UTC

+ Response 200 (application/json)

    [BlockedFile][]


### Delete BlockedFile [DELETE]
Delete a BlockedFile.

+ Request 
    + Header

            Authorization: RvPtP0QB7iIun1ehwheD4YUo7+fYfw7/ywl+HsC5Ddk=
            x-blocker-date: Wed, 28 Jan 2015 10:42:13 UTC

+ Response 204
